openapi: 3.0.3
info:
  title: SessionServer
  description: A microservice that provides services to hold logged in users sessions
  version: 1.3.1
  contact:
    name: Edson Manuel Carballo Vera
    email: edsonmanuelcarballovera@gmail.com
    url: https://twitter.com/EdsonManuelVera
servers:
  - url: 'http://clayrite.ddns.net:42100'
    description: Alpha testing
paths:
  /session:
    $ref: './session.yaml'